"""
Streamlit app to inspect GSW structures generated by generate_gsws_frames.py.

Usage:
    streamlit run playground/sleep_time/gsw_inspector.py
"""

import json
import re
import sys
from pathlib import Path

import openai
import streamlit as st
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent.parent / ".env")

# Add src to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

from gsw_memory.memory.models import GSWStructure

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
DATA_DIR = Path(__file__).parent.parent.parent / "data" / "sleep_time" / "frames"
NETWORKS_OUTPUT_DIR = DATA_DIR / "networks_output"
TITLE_MAPPING_PATH = DATA_DIR / "title_to_doc_idx.json"
ARTICLES_DIR = DATA_DIR / "articles" / "individual"

st.set_page_config(page_title="GSW Inspector", layout="wide", initial_sidebar_state="expanded")


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
@st.cache_data
def load_title_mapping() -> dict[str, int]:
    if TITLE_MAPPING_PATH.exists():
        with open(TITLE_MAPPING_PATH) as f:
            return json.load(f)
    return {}


@st.cache_data
def load_gsw(path: str) -> dict | None:
    p = Path(path)
    if not p.exists():
        return None
    with open(p) as f:
        return json.load(f)


def discover_runs() -> list[str]:
    if not NETWORKS_OUTPUT_DIR.exists():
        return []
    runs = sorted(
        [d.name for d in NETWORKS_OUTPUT_DIR.iterdir() if d.is_dir() and d.name.startswith("frames_")],
        reverse=True,
    )
    return runs


def discover_docs(run_dir: Path) -> list[int]:
    networks_dir = run_dir / "networks"
    if not networks_dir.exists():
        return []
    doc_dirs = [d for d in networks_dir.iterdir() if d.is_dir() and d.name.startswith("doc_")]
    indices = sorted(int(d.name.split("_")[1]) for d in doc_dirs)
    return indices


def _sanitize_filename(title: str) -> str:
    """Convert article title to a safe filename (matches generate_gsws_frames.py)."""
    name = re.sub(r'[<>:"/\\|?*]', '_', title)
    name = name.strip('. ')
    return name[:200]


@st.cache_data
def load_article_text(title: str) -> str | None:
    """Load the raw Wikipedia article text for a given title."""
    filename = _sanitize_filename(title) + ".txt"
    path = ARTICLES_DIR / filename
    if path.exists():
        return path.read_text(encoding="utf-8")
    return None


def build_entity_lookup(gsw: GSWStructure) -> dict[str, str]:
    """Map entity id -> entity name."""
    return {e.id: e.name for e in gsw.entity_nodes}


VERIFY_PROMPT = """\
You are an expert evaluator assessing the quality of a structured knowledge extraction from a source article.

The extraction system produces:
- **Entity nodes**: named entities with roles (e.g. "person", "organization") and states (attributes/descriptors)
- **Verb phrase nodes**: actions/relationships connecting entities
- **Questions**: factual questions derived from verb phrases, with answer entity references

## Source Article (raw input)
{article_text}

## Extracted Structure (output)

### Entities ({num_entities} total)
{entities_text}

### Verb Phrases & Questions ({num_vps} verb phrases, {num_questions} questions)
{vp_text}

---

Evaluate the extraction on these dimensions (score 1-10 each):

1. **Completeness**: Are the key entities, events, and relationships from the article captured? List important entities or facts that are missing.
2. **Accuracy**: Are the extracted entities, roles, states, verb phrases, and question-answer pairs faithful to the source text? List any hallucinated or incorrect extractions.
3. **Question Quality**: Are the generated questions meaningful, specific, and correctly answerable from the article? Do the answer references point to the right entities?
4. **Structure Quality**: Are entity roles and states well-chosen? Are verb phrases clear and semantically meaningful as relationship descriptors?

Respond in JSON:
{{
    "completeness": {{"score": <1-10>, "explanation": "<brief>", "missing_entities": ["<key entities not captured>"]}},
    "accuracy": {{"score": <1-10>, "explanation": "<brief>", "errors": ["<any incorrect extractions>"]}},
    "question_quality": {{"score": <1-10>, "explanation": "<brief>", "bad_questions": ["<problematic questions>"]}},
    "structure_quality": {{"score": <1-10>, "explanation": "<brief>"}},
    "overall_score": <1-10>,
    "summary": "<2-3 sentence overall assessment>"
}}"""


def _format_gsw_for_prompt(gsw: GSWStructure) -> tuple[str, str, int, int, int]:
    """Format GSW into human-readable text for the verification prompt."""
    entity_lookup = {e.id: e.name for e in gsw.entity_nodes}

    # Entities
    entity_lines = []
    for e in gsw.entity_nodes:
        roles = "; ".join(f"{r.role} [{', '.join(r.states)}]" for r in e.roles if r.states)
        if not roles:
            roles = "; ".join(r.role for r in e.roles)
        line = f"- {e.name} ({e.id}): {roles}"
        if e.summary:
            line += f" | Summary: {e.summary[:150]}"
        entity_lines.append(line)
    entities_text = "\n".join(entity_lines) if entity_lines else "(none)"

    # Verb phrases + questions
    vp_lines = []
    num_questions = 0
    for vp in gsw.verb_phrase_nodes:
        vp_lines.append(f"- [{vp.id}] \"{vp.phrase}\"")
        for q in vp.questions:
            num_questions += 1
            answer_names = [entity_lookup.get(a, a) for a in q.answers]
            vp_lines.append(f"    Q: {q.text}")
            vp_lines.append(f"    A: {', '.join(answer_names)}")
    vp_text = "\n".join(vp_lines) if vp_lines else "(none)"

    return entities_text, vp_text, len(gsw.entity_nodes), len(gsw.verb_phrase_nodes), num_questions


@st.cache_data(show_spinner="Running GPT-4o verification...")
def run_verification(article_text: str, entities_text: str, vp_text: str,
                     num_entities: int, num_vps: int, num_questions: int) -> dict:
    """Call GPT-4o to verify GSW extraction quality."""
    client = openai.OpenAI()
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are an expert knowledge extraction evaluator. Always respond with valid JSON."},
            {"role": "user", "content": VERIFY_PROMPT.format(
                article_text=article_text[:15000],
                entities_text=entities_text,
                vp_text=vp_text,
                num_entities=num_entities,
                num_vps=num_vps,
                num_questions=num_questions,
            )},
        ],
        temperature=0.0,
        response_format={"type": "json_object"},
    )
    content = response.choices[0].message.content
    try:
        return json.loads(content)
    except json.JSONDecodeError:
        json_match = re.search(r"\{.*\}", content, re.DOTALL)
        if json_match:
            return json.loads(json_match.group())
        return {"error": "Failed to parse response", "raw": content}


# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------
st.sidebar.title("GSW Inspector")

runs = discover_runs()
if not runs:
    st.error(f"No runs found in {NETWORKS_OUTPUT_DIR}")
    st.stop()

selected_run = st.sidebar.selectbox("Run", runs)
run_dir = NETWORKS_OUTPUT_DIR / selected_run

# Title mapping (inverted: doc_idx -> title)
title_mapping = load_title_mapping()
idx_to_title = {v: k for k, v in title_mapping.items()}

# Discover documents
doc_indices = discover_docs(run_dir)
if not doc_indices:
    st.sidebar.warning("No documents in this run.")
    st.stop()

# Build display labels
doc_labels = {i: f"doc_{i}: {idx_to_title.get(i, '(unknown)')}" for i in doc_indices}
selected_doc_idx = st.sidebar.selectbox(
    "Document",
    doc_indices,
    format_func=lambda i: doc_labels[i],
)

# Load GSW
gsw_path = run_dir / "networks" / f"doc_{selected_doc_idx}" / f"gsw_{selected_doc_idx}_0.json"
gsw_data = load_gsw(str(gsw_path))

if gsw_data is None:
    st.sidebar.error(f"GSW file not found: {gsw_path}")
    st.stop()

gsw = GSWStructure.from_json(gsw_data)
entity_lookup = build_entity_lookup(gsw)

# Sidebar metrics
total_entities = len(gsw.entity_nodes)
total_vps = len(gsw.verb_phrase_nodes)
total_questions = sum(len(vp.questions) for vp in gsw.verb_phrase_nodes)

st.sidebar.divider()
st.sidebar.metric("Entities", total_entities)
st.sidebar.metric("Verb Phrases", total_vps)
st.sidebar.metric("Questions", total_questions)

# ---------------------------------------------------------------------------
# Main area
# ---------------------------------------------------------------------------
title = idx_to_title.get(selected_doc_idx, f"doc_{selected_doc_idx}")
st.title(title)

tab_overview, tab_entities, tab_questions, tab_input, tab_verify, tab_raw = st.tabs(
    ["Overview", "Entity Explorer", "Questions", "Raw Input", "LLM Verify", "Raw JSON"]
)

# ---- Overview ----
with tab_overview:
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Entities", total_entities)
    col2.metric("Verb Phrases", total_vps)
    col3.metric("Questions", total_questions)
    col4.metric("Avg Q/VP", f"{total_questions / total_vps:.1f}" if total_vps else "0")

    st.subheader("Entities")
    entity_rows = []
    for e in gsw.entity_nodes:
        roles_str = ", ".join(r.role for r in e.roles)
        states_str = ", ".join(s for r in e.roles for s in r.states)
        entity_rows.append({
            "ID": e.id,
            "Name": e.name,
            "Roles": roles_str,
            "States": states_str[:80] + ("..." if len(states_str) > 80 else ""),
            "Summary": (e.summary or "")[:100] + ("..." if e.summary and len(e.summary) > 100 else ""),
        })
    if entity_rows:
        st.dataframe(entity_rows, use_container_width=True, hide_index=True)

    st.subheader("Verb Phrases")
    vp_rows = []
    for vp in gsw.verb_phrase_nodes:
        vp_rows.append({
            "ID": vp.id,
            "Phrase": vp.phrase,
            "Questions": len(vp.questions),
        })
    if vp_rows:
        st.dataframe(vp_rows, use_container_width=True, hide_index=True)

# ---- Entity Explorer ----
with tab_entities:
    entity_names = [f"{e.id}: {e.name}" for e in gsw.entity_nodes]
    if not entity_names:
        st.info("No entities in this GSW.")
    else:
        selected_entity_label = st.selectbox("Select entity", entity_names)
        selected_entity_id = selected_entity_label.split(":")[0].strip()
        entity = gsw.get_entity_by_id(selected_entity_id)

        if entity:
            st.subheader(entity.name)

            # Roles
            if entity.roles:
                st.markdown("**Roles & States**")
                for r in entity.roles:
                    states = ", ".join(r.states) if r.states else "(none)"
                    st.markdown(f"- **{r.role}**: {states}")

            # Summary
            if entity.summary:
                st.markdown("**Summary**")
                st.write(entity.summary)

            # Related verb phrases and questions
            st.divider()
            st.markdown("**Related Questions** (where this entity is an answer)")
            found = False
            for vp in gsw.verb_phrase_nodes:
                for q in vp.questions:
                    if entity.id in q.answers:
                        found = True
                        answer_names = [entity_lookup.get(a, a) for a in q.answers]
                        st.markdown(
                            f"- *{vp.phrase}* — **{q.text}**\n"
                            f"  - Answers: {', '.join(answer_names)}"
                        )
            if not found:
                st.caption("No questions reference this entity as an answer.")

# ---- Questions ----
with tab_questions:
    search = st.text_input("Search questions", "")

    for vp in gsw.verb_phrase_nodes:
        for q in vp.questions:
            if search and search.lower() not in q.text.lower():
                continue
            answer_names = [entity_lookup.get(a, a) for a in q.answers]
            with st.expander(f"{q.text}"):
                st.markdown(f"**Verb Phrase**: {vp.phrase}")
                st.markdown(f"**Answers**: {', '.join(answer_names)}")
                st.markdown(f"**Question ID**: {q.id} | **VP ID**: {vp.id}")

# ---- Raw Input ----
with tab_input:
    article_text = load_article_text(title)
    if article_text:
        st.text_area("Wikipedia Article Text", article_text, height=600, disabled=True)
    else:
        st.warning(f"Article text not found. Expected at: {ARTICLES_DIR / (_sanitize_filename(title) + '.txt')}")

# ---- LLM Verify ----
with tab_verify:
    article_text = load_article_text(title)
    if not article_text:
        st.warning("Cannot verify: article text not found.")
    else:
        entities_text, vp_text, n_ent, n_vp, n_q = _format_gsw_for_prompt(gsw)

        # Show what the verifier will see
        left, right = st.columns(2)
        with left:
            st.subheader("Raw Input (article)")
            st.text_area("Article text", article_text[:15000], height=300, disabled=True, key="verify_article")
        with right:
            st.subheader("Structured Output (GSW)")
            st.text_area("Entities", entities_text, height=150, disabled=True, key="verify_entities")
            st.text_area("Verb Phrases & Questions", vp_text, height=150, disabled=True, key="verify_vps")

        st.divider()

        if st.button("Run Verification (GPT-4o)"):
            result = run_verification(article_text, entities_text, vp_text, n_ent, n_vp, n_q)

            if "error" in result:
                st.error(f"Verification failed: {result['error']}")
                if "raw" in result:
                    st.code(result["raw"])
            else:
                # Overall score
                overall = result.get("overall_score", "?")
                st.markdown(f"### Overall Score: {overall}/10")
                st.markdown(result.get("summary", ""))

                st.divider()

                # Dimension scores
                col1, col2, col3, col4 = st.columns(4)
                dims = [
                    ("completeness", col1),
                    ("accuracy", col2),
                    ("question_quality", col3),
                    ("structure_quality", col4),
                ]
                for dim_name, col in dims:
                    dim = result.get(dim_name, {})
                    col.metric(dim_name.replace("_", " ").title(), f"{dim.get('score', '?')}/10")

                # Detailed explanations
                for dim_name, _ in dims:
                    dim = result.get(dim_name, {})
                    if dim:
                        with st.expander(dim_name.replace("_", " ").title()):
                            st.write(dim.get("explanation", ""))
                            if dim.get("missing_entities"):
                                st.markdown("**Missing entities:** " + ", ".join(dim["missing_entities"]))
                            if dim.get("errors"):
                                st.markdown("**Errors:** " + ", ".join(dim["errors"]))
                            if dim.get("bad_questions"):
                                st.markdown("**Problematic questions:** " + ", ".join(dim["bad_questions"]))

                # Raw verification JSON
                with st.expander("Raw verification result"):
                    st.json(result)

# ---- Raw JSON ----
with tab_raw:
    st.json(gsw_data)
